version: '3'
services:
  web:
    container_name: "toastedDenWebsite"
    image: nginx:alpine
    volumes:
      - ./website:/usr/share/nginx/html
    ports:
      - "8095:80"
    restart: always
